### ISSUE TITLE
Broken with Vegafusion-Jupyter 0.0.2+

### ISSUE THREAD

**Issue by DavidIngraham** [MarcSkovMadsen/panel-vegafusion#1]
With the minimum example from the readme I get the following output:

```
File 'vegafusion_panel.py', line 16, in <module>:
from vegafusion_jupyter.runtime import runtime Traceback (most recent call last):
  File "C:\Users\ding\.conda\envs\py38_64\lib\site-packages\bokeh\application\handlers\code_runner.py", line 231, in run
    exec(self._code, module.__dict__)
  File "C:\Users\ding\source\repos\novatellogtools\pynovatel\plotting_utils\panel_test.py", line 3, in <module>
    from panel_vegafusion import VegaFusion
  File "C:\Users\ding\.conda\envs\py38_64\lib\site-packages\panel_vegafusion\__init__.py", line 38, in <module>
    from .vegafusion_panel import VegaFusion
  File "C:\Users\ding\.conda\envs\py38_64\lib\site-packages\panel_vegafusion\vegafusion_pane.py", line 16, in <module>
    from vegafusion_jupyter.runtime import runtime
ModuleNotFoundError: No module named 'vegafusion_jupyter.runtime'
```

From what I can tell,  the vegafusion_jupyter.runtime module has not existed since 0.2.0
https://github.com/hex-inc/vegafusion/blob/v0.0.2/python/vegafusion-jupyter/vegafusion_jupyter/__init__.py

**Comment by MarcSkovMadsen** [comment]
Yes. Panel-vegafusion needs an update/ re-implementation now that Vega-fusion 1.0 has arrived.
